name: widgetbook
description: A flutter storybook that helps professionals and teams to catalogue their widgets.
version: 1.0.2
homepage: https://www.widgetbook.io?utm_source=youtube&utm_medium=link&utm_campaign=widgetbook
repository: https://github.com/widgetbook/widgetbook
issue_tracker: https://github.com/widgetbook/widgetbook/issues
documentation: https://github.com/widgetbook/widgetbook/tree/main/packages/widgetbook

environment:
  sdk: ">=2.17.0"
  flutter: ">=3.0.0"

dependencies:
  collection: ^1.16.0
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  meta: ^1.7.0
  vector_math: ^2.1.2
  widgetbook_models: any

# for development
dependency_overrides:
  widgetbook_models:
    path: ../widgetbook_models

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^3.0.0

flutter:
  assets:
    - google_fonts/
  fonts:
    - family: Nunito
      fonts:
        - asset: google_fonts/Nunito-Black.ttf
        - asset: google_fonts/Nunito-BlackItalic.ttf
        - asset: google_fonts/Nunito-Bold.ttf
        - asset: google_fonts/Nunito-BoldItalic.ttf
        - asset: google_fonts/Nunito-ExtraBold.ttf
        - asset: google_fonts/Nunito-ExtraBoldItalic.ttf
        - asset: google_fonts/Nunito-ExtraLight.ttf
        - asset: google_fonts/Nunito-ExtraLightItalic.ttf
        - asset: google_fonts/Nunito-Italic.ttf
        - asset: google_fonts/Nunito-Light.ttf
        - asset: google_fonts/Nunito-LightItalic.ttf
        - asset: google_fonts/Nunito-Regular.ttf
        - asset: google_fonts/Nunito-SemiBold.ttf
        - asset: google_fonts/Nunito-SemiBoldItalic.ttf

